project:
  output-dir: _output
  type: book

book:
  title : "Analysis of Citibikes - Big Data"
  chapters:
    - index.qmd
    - etl.qmd
    - analysis.qmd
    - monitoring.qmd
    - spatial_informations.qmd
  # downloads: [pdf]

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    grid:
      body-width: 1030px
      # sidebar-width: 200px
      # margin-width: 70px  
  # pdf format hardly compatible with altair
  # pdf:
  #   theme: cosmo
  #   title: "Report"
  #   toc: true
  #   geometry:
  #     - top=18.4mm
  #     - left=25.4mm
  #     - right=25.4mm
  #     - bottom=25.4mm